name: Test ScheduleBot

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
  workflow_run:
    workflows: [ build ]
    types: [ completed ]
    
  workflow_call: 
    
jobs: 
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      
      - name: Run tests
        run: dotnet test ScheduleBot.Tests/ScheduleBot.Tests.csproj